@StudifyAPI_HostAddress = https://localhost:7103

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXlsZW5lQGdtYWlsLmNvbSIsImlkIjoiMyIsImp0aSI6ImZhNjgwNjM3LTMwODMtNGNkOC1iYjdiLTEzMTg4YzYyMjZhYiIsImV4cCI6MTc2NDU1NjE1NywiaXNzIjoiU3R1ZGlmeUFQSSIsImF1ZCI6IlN0dWRpZnlVc2VycyJ9.jrPoOuXU26wIE2DQpI5CPP-ZbtaZ5m_DNtsaFtNsXpc
// Get all Users
GET {{StudifyAPI_HostAddress}}/api/users
Authorization: Bearer {{token}}
###

// Sign Up
POST {{StudifyAPI_HostAddress}}/api/users
Content-Type: application/json

{
  "Firstname": "Maylene",
  "Lastname": "Talisic",
  "Email": "Maylene@gmail.com",
  "Password": "maliklik"
}

###

// Login
POST {{StudifyAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "Email": "Maylene@gmail.com",
  "Password": "maliklik"
}

###

@id=0
DELETE {{StudifyAPI_HostAddress}}/api/users/{{id}}

###

GET {{StudifyAPI_HostAddress}}/api/users/{{id}}

###

// Update
PATCH {{StudifyAPI_HostAddress}}/api/users/{{id}}
Content-Type: application/json

{
  //UserPatchDTO
}

###

