@StudifyAPI_HostAddress = https://localhost:7103

// USER
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYW1hd0BnbWFpbC5jb20iLCJ1c2VySWQiOiIyIiwianRpIjoiYjUzMGVmNGItNWZmMS00YWI5LWI1YzUtN2MxODA3NWQ1MGQ1IiwiZXhwIjoxNzY0OTMzNTkwLCJpc3MiOiJTdHVkaWZ5QVBJIiwiYXVkIjoiU3R1ZGlmeVVzZXJzIn0.4tPFmXUj-_eI0R3ssFhM7BDSYbv8R1qs-EXQGADqvFY

// Get all users
GET {{StudifyAPI_HostAddress}}/api/users
Authorization: Bearer {{token}}
###

// Sign Up
POST {{StudifyAPI_HostAddress}}/api/users
Content-Type: application/json

{
  "Firstname": "ducay",
  "Lastname": "mamaw",
  "Email": "mamaw@gmail.com",
  "Password": "mamaw123"
}

###

// Login
POST {{StudifyAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "Email": "mamaw@gmail.com",
  "Password": "mamaw123"
} 

###

// Delete user account
DELETE {{StudifyAPI_HostAddress}}/api/users/me
Authorization: Bearer {{token}}
###

// Get profile
GET {{StudifyAPI_HostAddress}}/api/users/me
Authorization: Bearer {{token}}
###

// Update
PATCH {{StudifyAPI_HostAddress}}/api/users/me
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Firstname": "Pokemon"
}

###

// Logout
POST {{StudifyAPI_HostAddress}}/api/users/me/logout
Authorization: Bearer {{token}}

###



// TASK
// Create task
POST {{StudifyAPI_HostAddress}}/api/tasks
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Title": "Study Science"
}

###


// Get all tasks
GET {{StudifyAPI_HostAddress}}/api/tasks/me
Authorization: Bearer {{token}}
###


// Patch task
@taskId=8
PATCH {{StudifyAPI_HostAddress}}/api/tasks/{{taskId}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "isCompleted": true
}


###

// Delete task
DELETE {{StudifyAPI_HostAddress}}/api/tasks/{{taskId}}
Authorization: Bearer {{token}}
###



// POMODRO
GET {{StudifyAPI_HostAddress}}/api/pomodoros
Authorization: Bearer {{token}}
###


// STREAKS

// get current streak
GET {{StudifyAPI_HostAddress}}/api/streaks/me
Authorization: Bearer {{token}}
###

// update streak
POST {{StudifyAPI_HostAddress}}/api/streaks
Authorization: Bearer {{token}}
###



// FRIEND REQUESTS

// Get all sent requests
GET {{StudifyAPI_HostAddress}}/api/friendrequests/sent/me
Authorization: Bearer {{token}}
###

// Get all receive requests
GET {{StudifyAPI_HostAddress}}/api/friendrequests/received/me
Authorization: Bearer {{token}}
###



// Send request using email
POST {{StudifyAPI_HostAddress}}/api/friendrequests
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Email": "jerhon@gmail.com"
}

###

// Accepting received request (To be implemented)
POST {{StudifyAPI_HostAddress}}/api/friendrequests/1/accept
Authorization: Bearer {{token}}
###

// Reject received request
DELETE {{StudifyAPI_HostAddress}}/api/friendrequests/3/reject
Authorization: Bearer {{token}}
###

// Cancel sent request
DELETE {{StudifyAPI_HostAddress}}/api/friendrequests/3/cancel
Authorization: Bearer {{token}}
###